# Generated by Django 5.0.3 on 2024-07-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_antenna_available_dual_beam_antenna_dual_beam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antenna",
            name="login_time",
        ),
    ]
