# Generated by Django 5.0.3 on 2024-07-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_antenna_login_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antenna",
            name="create_time",
        ),
    ]
