# Generated by Django 5.0.3 on 2024-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_task_id_meta_task_list_belong_to_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_list",
            name="status",
            field=models.CharField(
                choices=[
                    ("运行中", "运行中"),
                    ("终止", "终止"),
                    ("运行结束", "运行结束"),
                    ("抢占结束", "抢占结束"),
                ],
                max_length=32,
            ),
        ),
    ]
